# -*- encoding : utf-8 -*-
Putterking::Application.routes.draw do
  root to: 'static_pages#home'
  match '/app', to: 'static_pages#app'
  match '/en/app', to: 'static_pages#app'
  match '/en/about', to: 'static_pages#about'
  match '/about', to: 'static_pages#about'
  match '/en/content/education', to: 'static_pages#math'
  match '/en/content/education-physics', to: 'static_pages#physics'
  match '/physics', to: 'static_pages#physics'
  match '/en/content/education-math', to: 'static_pages#math'
  match '/math', to: 'static_pages#math'
  match '/home', to: 'static_pages#home'
  match '/en/scavenger-hunt/archive', to: 'static_pages#pksh1'
  match '/pksh1', to: 'static_pages#pksh1'
  match '/pksh2', to: 'static_pages#pksh2'
  match '/en/content/top-10-nostalgic-miniature-golf-obstacles', to: 'blogs#nostalgic'
  match '/blog/top-10-nostalgic-miniature-golf-obstacles', to: 'blogs#nostalgic', :as => 'nostalgic'
  match '/en/content/putting-away-parkinson’s', to: 'blogs#parkinson'
  match '/blog/putting-away-parkinson', to: 'blogs#parkinson', :as => 'parkinson'
  match '/blog/dentist-precision', to: 'blogs#dentist', :as => 'dentist'
  match '/en/content/dentist’s-precision', to: 'blogs#dentist'
  match '/en/content/adventures-crazy-world-minigolf-tour', to: 'blogs#crazy'
  match '/blog/adventures-crazy-world-minigolf-tour', to: 'blogs#crazy', :as => 'crazy'
  match '/en/content/insight-creativity-and-imagination', to: 'blogs#creativity'
  match '/blog/insight-creativity-and-imagination', to: 'blogs#creativity', :as => 'creativity'
  match '/blog/putter-king-scavenger-hunt-riddle', to: 'blogs#riddle', :as => 'riddle'
  match '/en/content/putter-king-scavenger-hunt-riddle-answer', to: 'blogs#riddle'
  match '/blog/finger-pulse-minigolf-world', to: 'blogs#pulse', :as => 'pulse'
  match '/en/content/finger-pulse-minigolf-world', to: 'blogs#pulse'
  match '/blog/miniature-golf-down-under', to: 'blogs#under', :as => 'under'
  match '/en/content/miniature-golf-down-under', to: 'blogs#under'
  match '/blog/greatest-nutter-ever-hold-putter', to: 'blogs#nutter', :as => 'nutter'
  match '/en/content/greatest-nutter-ever-hold-putter', to: 'blogs#nutter'
  match '/blog/minigolf-machine', to: 'blogs#machine', :as => 'machine'
  match '/en/content/minigolf-machine', to: 'blogs#machine'
  match '/blog/minigolf-ninjas', to: 'blogs#ninjas', :as => 'ninjas'
  match '/en/content/minigolf-ninjas', to: 'blogs#ninjas'
  match '/blog', to: 'blogs#index'
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
end
